services:
  - type: web
    name: luminai-backend
    env: python
    region: singapore
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: MONGO_URL
        value: "mongodb+srv://mrpkreddy07:Pranav%402007@luminai.a55onpu.mongodb.net/lumin_ai_open?authSource=admin&retryWrites=true&w=majority"
      - key: SECRET_KEY
        value: "lumin24csb0a7724csb0b1524csb0b24"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dxjj5lr7v"
      - key: CLOUDINARY_API_KEY
        value: "968426229835983"
      - key: CLOUDINARY_API_SECRET
        value: "b423kNt5Vzjrp3gZT4OQlTiXlao"
      - key: SMTP_EMAIL
        value: "mrpkreddy07@gmail.com"
      - key: SMTP_PASSWORD
        value: "qvzvleuyjsegxayn"
      - key: ENABLE_FACE_MATCH
        value: "false"
      - key: VITE_SIMLI_API_KEY
        value: "ypq57rbupjcm08dnqkxiv9"
      - key: VITE_SIMLI_FACE_ID
        value: "cace3ef7-a4c4-425d-a8cf-a5358eb0c427"
      - key: GEMINI_API_KEY
        sync: false # Set this value manually in the Render dashboard
      - key: SEED_DEV_DATA
        value: "true" # Will seed the first time, can be disabled later
